package com.uep.freelance.model;

public enum JobCategory {
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    CLOUD_COMPUTING,
    CYBERSECURITY,
    DEVOPS,
    FRONTEND,
    BACKEND,
    FULLSTACK,
    UI_UX_DESIGN,
    GRAPHICS_DESIGN,
    CONTENT_WRITING,
    SEO,
    DIGITAL_MARKETING,
    OTHER
}
